### ISSUE TITLE
[🐛 Bug]: Using starter toolkit does not work using yarn

### ISSUE THREAD

**Issue by marcial199545** [webdriverio/create-wdio#305] opened 2022-12-08 22:38 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.14.2

### Mode

Standalone Mode

### What happened?

While trying to use the starter toolkit, I keep getting this error. 
```
marccaballero@LM-SJC-11016683 checkout % yarn create wdio .                          
yarn create v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-wdio@8.1.0" with binaries:
      - create-wdio
[#############] 13/13
                 -:...........................-:.
                 +                              +
              `` +      `...`        `...`      + `
            ./+/ +    .:://:::`    `::///::`  ` + ++/.
           .+oo+ +    /:+ooo+-/    /-+ooo+-/ ./ + +oo+.
           -ooo+ +    /-+ooo+-/    /-+ooo+-/ .: + +ooo.
            -+o+ +    `::///:-`    `::///::`    + +o+-
             ``. /.     `````        `````     .: .``
                  .----------------------------.
           `-::::::::::::::::::::::::::::::::::::::::-`
          .+oooo/:------------------------------:/oooo+.
      `.--/oooo-                                  :oooo/--.`
    .::-``:oooo`                                  .oooo-``-::.
  ./-`    -oooo`--.: :.--                         .oooo-    `-/.
 -/`    `-/oooo////////////////////////////////////oooo/.`    `/-
`+`   `/+oooooooooooooooooooooooooooooooooooooooooooooooo+:`   .+`
-/    +o/.:oooooooooooooooooooooooooooooooooooooooooooo:-/o/    +.
-/   .o+  -oooosoooososssssooooo------------------:oooo- `oo`   +.
-/   .o+  -oooodooohyyssosshoooo`                 .oooo-  oo.   +.
-/   .o+  -oooodooysdooooooyyooo` `.--.``     .:::-oooo-  oo.   +.
-/   .o+  -oooodoyyodsoooooyyooo.//-..-:/:.`.//.`./oooo-  oo.   +.
-/   .o+  -oooohsyoooyysssysoooo+-`     `-:::.    .oooo-  oo.   +.
-/   .o+  -ooooosooooooosooooooo+//////////////////oooo-  oo.   +.
-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.
-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.
-+////o+` -oooo---:///:----://::------------------:oooo- `oo////+-
+ooooooo/`-oooo``:-```.:`.:.`.+/-    .::::::::::` .oooo-`+ooooooo+
oooooooo+`-oooo`-- `/` .:+  -/-`/`   .::::::::::  .oooo-.+oooooooo
+-/+://-/ -oooo-`:`.o-`:.:-````.:    .///:``````  -oooo-`/-//:+:-+
: :..--:-:.+ooo+/://o+/-.-:////:-....-::::-....--/+ooo+.:.:--.-- /
- /./`-:-` .:///+/ooooo/+///////////////+++ooooo/+///:. .-:.`+./ :
:-:/.           :`ooooo`/`              .:.ooooo :           ./---
                :`ooooo`/`              .:.ooooo :
                :`ooooo./`              .:-ooooo :
                :`ooooo./`              .:-ooooo :
            `...:-+++++:/.              ./:+++++-:...`
           :-.````````/../              /.-:````````.:-
          -/::::::::://:/+             `+/:+::::::::::+.
          :oooooooooooo++/              +++oooooooooooo-
 
                           Webdriver.IO
              Next-gen browser and mobile automation
                    test framework for Node.js


Installing @wdio/cli to initialize project...
file:///Users/marccaballero/.config/yarn/global/node_modules/create-wdio/build/utils.js:16
                return reject(new Error((error && error.message) ||
                              ^

Error: Error calling: npm install --save-dev --loglevel error @wdio/cli@latest
    at ChildProcess.<anonymous> (file:///Users/marccaballero/.config/yarn/global/node_modules/create-wdio/build/utils.js:16:31)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
error Command failed.
Exit code: 1
Command: /Users/marccaballero/.yarn/bin/create-wdio
Arguments: .
Directory: /Users/marccaballero/checkout/checkout
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

Initially I though it may be related to the M1 chip since I have noticed multiple libraries have had issue with this chip, but I tested in a previous version of a mac pro and it is still failing for the same reason, as you can see there's no output message shown in the error so this is what I can deliver

### What is your expected behavior?

That the toolkit works or having documentation to manually integrate the library

### How to reproduce the bug.

Using node `v16.14.2`
running `yarn create wdio .`

### Relevant log output

```typescript
marccaballero@LM-SJC-11016683 checkout % yarn create wdio .                          
yarn create v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-wdio@8.1.0" with binaries:
      - create-wdio
[#############] 13/13
                 -:...........................-:.
                 +                              +
              `` +      `...`        `...`      + `
            ./+/ +    .:://:::`    `::///::`  ` + ++/.
           .+oo+ +    /:+ooo+-/    /-+ooo+-/ ./ + +oo+.
           -ooo+ +    /-+ooo+-/    /-+ooo+-/ .: + +ooo.
            -+o+ +    `::///:-`    `::///::`    + +o+-
             ``. /.     `````        `````     .: .``
                  .----------------------------.
           `-::::::::::::::::::::::::::::::::::::::::-`
          .+oooo/:------------------------------:/oooo+.
      `.--/oooo-                                  :oooo/--.`
    .::-``:oooo`                                  .oooo-``-::.
  ./-`    -oooo`--.: :.--                         .oooo-    `-/.
 -/`    `-/oooo////////////////////////////////////oooo/.`    `/-
`+`   `/+oooooooooooooooooooooooooooooooooooooooooooooooo+:`   .+`
-/    +o/.:oooooooooooooooooooooooooooooooooooooooooooo:-/o/    +.
-/   .o+  -oooosoooososssssooooo------------------:oooo- `oo`   +.
-/   .o+  -oooodooohyyssosshoooo`                 .oooo-  oo.   +.
-/   .o+  -oooodooysdooooooyyooo` `.--.``     .:::-oooo-  oo.   +.
-/   .o+  -oooodoyyodsoooooyyooo.//-..-:/:.`.//.`./oooo-  oo.   +.
-/   .o+  -oooohsyoooyysssysoooo+-`     `-:::.    .oooo-  oo.   +.
-/   .o+  -ooooosooooooosooooooo+//////////////////oooo-  oo.   +.
-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.
-/   .o+  -oooooooooooooooooooooooooooooooooooooooooooo-  oo.   +.
-+////o+` -oooo---:///:----://::------------------:oooo- `oo////+-
+ooooooo/`-oooo``:-```.:`.:.`.+/-    .::::::::::` .oooo-`+ooooooo+
oooooooo+`-oooo`-- `/` .:+  -/-`/`   .::::::::::  .oooo-.+oooooooo
+-/+://-/ -oooo-`:`.o-`:.:-````.:    .///:``````  -oooo-`/-//:+:-+
: :..--:-:.+ooo+/://o+/-.-:////:-....-::::-....--/+ooo+.:.:--.-- /
- /./`-:-` .:///+/ooooo/+///////////////+++ooooo/+///:. .-:.`+./ :
:-:/.           :`ooooo`/`              .:.ooooo :           ./---
                :`ooooo`/`              .:.ooooo :
                :`ooooo./`              .:-ooooo :
                :`ooooo./`              .:-ooooo :
            `...:-+++++:/.              ./:+++++-:...`
           :-.````````/../              /.-:````````.:-
          -/::::::::://:/+             `+/:+::::::::::+.
          :oooooooooooo++/              +++oooooooooooo-
 
                           Webdriver.IO
              Next-gen browser and mobile automation
                    test framework for Node.js


Installing @wdio/cli to initialize project...
file:///Users/marccaballero/.config/yarn/global/node_modules/create-wdio/build/utils.js:16
                return reject(new Error((error && error.message) ||
                              ^

Error: Error calling: npm install --save-dev --loglevel error @wdio/cli@latest
    at ChildProcess.<anonymous> (file:///Users/marccaballero/.config/yarn/global/node_modules/create-wdio/build/utils.js:16:31)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
error Command failed.
Exit code: 1
Command: /Users/marccaballero/.yarn/bin/create-wdio
Arguments: .
Directory: /Users/marccaballero/checkout/checkout
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment] 2022-12-08 22:47
The problem is our [`shouldUseYarn`](https://github.com/webdriverio/create-wdio/blob/377ab31cdf7e20feeb610d8f11dcf57781248ca3/src/utils.ts#L31-L38) helper which currently is very dump and could be improved to use Yarn when other factors play in.

**Comment by christian-bromann** [comment] 2022-12-10 22:34
@marcial199545 after looking into this, it seems that it is unrelated to whether Yarn is installed or not. I wonder why `npm install --save-dev --loglevel error @wdio/cli@latest` is failing for you, have you tried to run it manually? Do you have NPM for some reasons not installed?

**Comment by MeganAlexia** [comment] 2023-01-10 12:29
Hello, I'm running into the exact same issue with yarn - NPM is installed and I am running on node v18.12.1, also a Macbook M1 Pro. Are there any updates on this by any chance?

**Comment by christian-bromann** [comment] 2023-01-11 08:15
> Are there any updates on this by any chance?

As you can see there are no updates. Any help on this issue would be appreciated.

**Comment by MeganAlexia** [comment] 2023-01-16 12:50
Hello! I realised this is due to incorrect peer dependencies in the project installation. This only triggers some warnings when running with `yarn` but fails completely when using `npm`. After solving the incorrect peer dependencies, the installation is working properly. 
However, I think the ultimate issue is that despite my project being setup with `yarn`, the installation steps through `create-wdio` are done with `npm`. This leads to the creation of a `package-lock.json` which I believe is incorrect (I would expect an update of my `yarn.lock`). 

I see there was a commit here to [better detect yarn project](https://github.com/webdriverio/create-wdio/commit/4ac06811864ce028d96ac1ae2397bc9a211703a6) but it looks like the pipeline has failed. I'm wondering if this was intended to solve similar issues that we have been facing?

I haven't had the chance to really dig into the project, so please let me know if this sounds incorrect!

**Comment by christian-bromann** [comment] 2023-01-17 19:42
> I see there was a commit here to [better detect yarn project](https://github.com/webdriverio/create-wdio/commit/4ac06811864ce028d96ac1ae2397bc9a211703a6) but it looks like the pipeline has failed. I'm wondering if this was intended to solve similar issues that we have been facing?

The change was released with the latest version.

> However, I think the ultimate issue is that despite my project being setup with `yarn`, the installation steps through `create-wdio` are done with `npm`.

Can you provide a way to reproduce this? There might be some approaches we have missed. Afaik it should not use NPM if Yarn is detected.

**Comment by christian-bromann** [comment] 2023-06-14 07:51
Closing due to inactivity.

**Closed by christian-bromann** 2023-06-14 07:51 UTC
Labels: bug, help wanted
